###############################################################
# Poisson regression with interrupted time series
###############################################################

rm(list = ls())

# SET OUTPUT DIRECTORY
OutputDirectory <- "./report_outputs/"
OutputDirectoryPaper <- "./report_outputs/figures_paper/"
OutputDirectoryData <- "../paper/data/clean/regression/"

# load packages
PACKAGES = c(
  "readxl", "writexl", "lubridate", "zoo", "ggplot2", "scales","reshape","boot","pander",
  "epicontacts", "tidyverse", "formattable", "igraph", "viridis", "ggthemes", "MASS"
)

# install packages if needed
for (pack_name in PACKAGES) {
  if (!pack_name %in% rownames(installed.packages()))
    install.packages(pack_name)
}

pacman::p_load(readxl, writexl, lubridate, zoo, ggplot2, scales, reshape, boot, pander,
               epicontacts, tidyverse, formattable, igraph, Hmisc, viridis,ggthemes, MASS)


# load functions
#####################################################
source("./functions/multiplot.R")

# Function to tidy Poisson regression output
glmtidy <- function(x, caption = ''){
  pander(tidy(x, exponentiate = TRUE, conf.int = TRUE),
         caption = caption)
}
# Function to tidy Poisson regression statistics
glmstats <- function(x){
  pander(glance(x))
}

# Load data
###############################################################
# Load data (generated by bxl_case_numbers_epicurve_20201218)
Filename <- "./data/clean/regression/casesBXL_age_count.Rdata"
load(Filename)

# Import dataset with the number of testes performed for 10-19 years old
load("./data/clean/tests_rate_1019.Rdata")

# Import test dataset
testsBE <- load("./data/clean/regression/testsBXL.Rdata")

######################################################
# PREAMBLE DATA

# Select the children aged 10-19
casesBXL_1019_counts_long <- subset(casesBXL_age_counts_long, casesBXL_age_counts_long$age_group == "10-19 years")

# Select the period of interest
tests_rate_1019_short <- subset(tests_rate_1019, tests_rate_1019$date>"2020-07-31" & date<"2020-10-01")


# Merge the two datasets
casesBXL_1019_tests <-  merge(casesBXL_1019_counts_long %>% ungroup(), tests_rate_1019_short  %>% ungroup(), by = "date", all = TRUE)
casesBXL_1019_tests$n_tests_1019 <- casesBXL_1019_tests$total

testsBXL = testsBXL[,c(1:4)]
names(testsBXL) = tolower(names(testsBXL))  
testsBXL = testsBXL %>%
  mutate(date = as.Date(date, format="%Y-%m-%d"))

casesBXL_1019_tests = left_join(casesBXL_1019_tests, testsBXL, by="date") %>%
  dplyr::rename(n_tests = "tests_all") %>%
  mutate(#test_fraction_1019 = n_tests_1019/n_tests,
    day =c(1:length(n_tests)),
    school = as.integer(school))


data=casesBXL_1019_tests %>% filter(date<=as.Date("2020-10-01")) %>%
  mutate(weekday = weekdays(date),
         weekend = ifelse(weekday%in%c("zaterdag", "zondag"),1,0))


# PLOT CORRELATIONS
########################################################################
ggplot(data, aes(x=n_tests_1019, y=n_cases/total_n_cases)) + geom_point()+
  geom_smooth(method = "gam", formula = y ~ s(x))+
  theme_bw()+
  ylab("cases")+
  xlab("Tests performed")

# SHOW CORRELATION NUMBER OF TESTS PERFORMED AND FRACTION OF 10-19
ggplot(data, aes(x=n_tests_1019, y=n_cases)) + geom_point()+
  geom_smooth(method = "gam", formula = y ~ s(x))+
  theme_bw()+
  ylab("cases")+
  xlab("Tests performed")

ggplot(data, aes(x=n_tests_1019, y=day)) + geom_point()+
  geom_smooth(method = "gam", formula = y ~ s(x))+
  theme_bw()+
  ylab("day")+
  xlab("Tests performed")

shapiro.test(data$n_cases/data$total_n_cases) # We can not assume normality
shapiro.test(data$n_tests_1019) # No normality
shapiro.test(data$day)

# Use non-parametric test for correlation
cor.test(data$n_cases, data$n_tests_1019, 
         method = "spearman")
# Use non-parametric test for correlation time and tests
cor.test(data$day, data$n_tests_1019, 
         method = "spearman")

#######################################################
# USED FOR PAPER

# Model : possion regression including the number of test performed for 10-19 olds (However, this is likely explained by time trend
# considering strong correlation between time and tests performed)
# Including the slope change (date*school interaction term)
# we parameterize it as an interaction between centered time and school indicator
min(data$day[data$school==1])

m1 <- glm(n_cases ~ offset(log(total_n_cases)) + day + school + I(day-36):school + n_tests_1019 + weekend, data=data,
          family="poisson")
summary(m1)
glmtidy(m1)

# # Excluding the slope change (date*school interaction term)
m2 <- glm(n_cases ~ offset(log(total_n_cases)) + day + school + n_tests_1019 + weekend, data=data,
          family='poisson')

summary(m2)
glmtidy(m2)

m3 <- glm(n_cases ~ offset(log(total_n_cases)) + day + n_tests_1019 + weekend, data=data,
          family='poisson')
summary(m3)
glmtidy(m3)

# Without testing
m4 <- glm(n_cases ~ offset(log(total_n_cases)) + day + school + weekend, data=data,
          family='poisson')
summary(m4)
glmtidy(m4)

# COMPARE MODEL FITS
#########################################################
AIC(m1,m2, m3, m4)


# PLOT MODEL FITS
#########################################################


# CREATE NEW DATASET WITHOUT WEEKEND AND TESTING FIXED
datanew <- data %>%# select(c(day, school, n_tests_1019, total_n_cases, weekend))%>%
  mutate(total_n_cases= mean(total_n_cases),
         n_tests_1019 = mean(n_tests_1019),
         weekend = 0
  )

# CREATE NEW DATASET WITHOUT WEEKEND AND TESTING FIXED
# datanew2 <- data %>%# select(c(day, school, n_tests_1019, total_n_cases, weekend))%>%
#   mutate(total_n_cases= mean(total_n_cases),
       #  n_tests_1019 = mean(n_tests_1019),
      #   weekend = 0
#  )



# We generate predicted values based on the model in order to create a plot
pred1 <- predict(m1, newdata= datanew, type ="link",se.fit=T)
pred2 <- predict(m3, newdata= datanew, type ="link",se.fit=T)

#The confidence interval on the linear predictor for model with weekend and testing variable:
critval <- 1.96 ## approx 95% CI
upr <- pred1$fit + (critval * pred1$se.fit)
lwr <- pred1$fit - (critval * pred1$se.fit)#/mean(casesBXL_1019_tests$total_n_cases)
fit <- pred1$fit#/mean(casesBXL_1019_tests$total_n_cases)

#Now for fit, upr and lwr we need to apply the inverse of the link function to them.
fit2 <- m1$family$linkinv(fit)/mean(data$total_n_cases)
upr2 <- m1$family$linkinv(upr)/mean(data$total_n_cases)
lwr2 <- m1$family$linkinv(lwr)/mean(data$total_n_cases)

#The confidence interval on the linear predictor for model with weekend and testing not variable:
critval_f <- 1.96 ## approx 95% CI
upr_f <- pred2$fit + (critval_f * pred2$se.fit)
lwr_f <- pred2$fit - (critval_f * pred2$se.fit)#/mean(casesBXL_1019_tests$total_n_cases)
fit_f <- pred2$fit#/mean(casesBXL_1019_tests$total_n_cases)

#Now for fit, upr and lwr we need to apply the inverse of the link function to them.
fit2_f <- m3$family$linkinv(fit_f)/mean(data$total_n_cases)
upr2_f <- m3$family$linkinv(upr_f)/mean(data$total_n_cases)
lwr2_f <- m3$family$linkinv(lwr_f)/mean(data$total_n_cases)



# This can then be plotted
fit_poisson <- ggplot(data) +
  geom_point(aes(x = date, y =n_cases/total_n_cases),size=3, alpha=0.5) +
  geom_vline(xintercept = as.Date("2020-09-01"), linetype=3) + 
  geom_line(aes(x = date, y = fit2),size=1) +
  geom_line(aes(x = date, y = fit2_f),size=1, linetype=1, col="red") +
  geom_line(aes(x = date, y = lwr2), linetype=2) +
  geom_line(aes(x = date, y = upr2), linetype=2) +
  labs(title="", x = "", y="Fraction of 10-19 years old cases") +
  scale_colour_discrete(name="Schools", labels=c("Closed", "Open")) +
  theme_bw() + 
  ylim(0,0.5) +
  theme(axis.text = element_text(size=15),
        axis.title=element_text(size=15),
        legend.text= element_text(size=15),
        legend.title= element_text(size=15),
        strip.text.x = element_text(size = 20),
        plot.title = element_text(size=22))
fit_poisson

# SAVE PLOT
pdf(file=paste0(OutputDirectoryPaper,"SuppFig5_20201218.pdf"), width=8, height=6)
fit_poisson
dev.off()

ggsave("poisson_fit_final.png", plot =fit_poisson, device="png", path = OutputDirectory, width=10,height=8)

